version: '3.7'
services:

   client:
      stdin_open: true
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3000:3000"
      volumes:
         - ./frontend:/app
         - /app/node_modules
      networks: 
         - frontend

   api:
      build: 
            context: ./backend
            dockerfile: Dockerfile
      command: gunicorn --bind 0.0.0.0:5000 --reload manage:app
      ports:
            - "5000:5000"
      environment:
            MONGODB_HOST: mongodb
            MONGODB_USERNAME: "apiuser"
            MONGODB_PASSWORD: "apipassword"
            POSTGRES_USER: "apiuser"
            POSTGRES_PASSWORD: "apipassword"
            POSTGRES_DB: "apidev"
            POSTGRES_PORT: 5432
      volumes:
            - ./backend:/app
      depends_on: 
            - mongodb
      networks:
            - frontend
            - backend

   db:
      image: postgres
      volumes:
            - postgresdata:/var/lib/postgresql/data
      environment:
            POSTGRES_USER: "apiuser"
            POSTGRES_PASSWORD: "apipassword"
            POSTGRES_DB: "apidev"
            POSTGRES_PORT: 5432
      networks:
            - backend

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge
volumes:
   postgresdata:
      driver: local